name: Build and Deploy

on:
  # Triggers the workflow on push or pull request events but only for the "dev" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: codehub-stage
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.TOKEN_GITHUB }}
          submodules: true

        # Update references
      - name: Git Sumbodule Update
        run: |
          git pull --recurse-submodules
          git submodule update --remote --recursive

      - name: Build and Deploy to server
        run: docker compose -f deployment/docker-compose.yml up -d --build
